### ISSUE TITLE
CartoDB labels cut off on long names

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#113]
http://iswp2017demo.elasticbeanstalk.com/entity/417

![image](https://cloud.githubusercontent.com/assets/697848/11979805/df2a0636-a95b-11e5-96a1-f2f7bffa741a.png)

@wilsaj - are you aware of a fix for this?

**Comment by jseppi** [comment]
One potential band-aid fix could be to split long names into multiple lines

**Comment by wilsaj** [comment]
Can also fix by increasing `buffer-size`: http://docs.cartodb.com/faqs/maps/#why-are-my-map-labels-cut-off

**Comment by jseppi** [comment]
Cool, thanks. I had it increased to 128 already, but some of the names are super long. I think the wrapping ended up looking better than really long labels anyways.
