### ISSUE TITLE
Header Text Adjustments

### ISSUE THREAD

**Issue by christoball** [TNRIS/iswp2017#131]
I have some proposed approaches for the header. I feel like the current one can be altered to be less plain.

### Proposal 1:
Separate out the DRAFT 2017 part - make the TWDB logo link to water plan and not water board site.
![title_mockup_1](https://cloud.githubusercontent.com/assets/1877550/12491976/8bcc5e0e-c043-11e5-9bdb-98a0646290f9.jpg)

### Proposal 2:
This might not work as well, but I did experience a little bit of User disconnect when I was trying to go back from the about page back to the main map.

Based on most website behavior, I'm used to clicking the main logo to the far left to go back to the main page of where I'm at. In this case, the water board logo takes me to the water board site.

If we keep it there, I would propose making it link to the main page of the water plan. Or, do something like the image below, making the water plan the prioritized element on the far left. 
![title_mockup_2](https://cloud.githubusercontent.com/assets/1877550/12492077/18646fa0-c044-11e5-8682-04be42c67271.jpg)

@jseppi @mateonnelson thoughts?

**Comment by jseppi** [comment]
Yeah, I like moving the title to the left, and I like the minor coloration/styling.
