### ISSUE TITLE
Title Labels for Context

### ISSUE THREAD

**Issue by christoball** [TNRIS/iswp2017#134]
Proposed labels for tables and bottom section.

I feel like these work pretty well
![countylabel_tables](https://cloud.githubusercontent.com/assets/1877550/12495611/50838986-c056-11e5-9336-4cef9e49009b.png)

![countylabel_decades](https://cloud.githubusercontent.com/assets/1877550/12495612/53b56764-c056-11e5-8eb7-0e5f422a4ba6.png)

**Comment by jseppi** [comment]
I think it looks a bit noisy to have the place name repeated so often. I think a user will know that they are looking at data for the place given at the top of the page. Census Reporter (whose design I am imitating) does not repeat the place throughout the page: http://censusreporter.org/profiles/16000US4805000-austin-tx/

Anyone else have opinions on this? @mateonnelson @wilsaj

**Comment by jseppi** [comment]
I implemented this and put it up on the demo page. The panel titles are shown on region, county, and entity views. Please let me know opinions.

**Comment by jseppi** [comment]
Went ahead and merged this in c6b532435d71192dd24ccf9f427cfa47e4746189
