### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#143]
Needs to be live (but non-search-indexed) by Feb 24 for Board review.

cc @wilsaj

**Comment by wilsaj** [comment]
everything's set up in our internal deployment repo, so should be no problem

**Comment by jseppi** [comment]
- [ ] set 2012 ISWP to 2012.texasstatewaterplan.org
- [ ] publish 2017 ISWP at 2017.texasstatewaterplan.org
- [ ] redirect texasstatewaterplan.org -> 2017.texasstatewaterplan.org

**Comment by jseppi** [comment]
All done and deployed!
