### ISSUE TITLE
Entity View - Sources map

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#153]
Once we have the sources mapping, we should add the date-selectable map only so that an entity can see what sources they rely on. And that map would have a single toggle either: current supplies or strategies

**Comment by adambreznicky** [comment]
hmmmm do you mean an additional map only in the entity view? currently i have it set up so that sources an entity uses are displayed in the lower theme map for themes supplies and strategies (as you have described). is this what you meant or did you have another idea in mind?

**Comment by jseppi** [comment]
Um, I don't remember what this meant :)

**Comment by adambreznicky** [comment]
Right on.  Time tends to do that.  
Based on what I think you were getting at,  I'm going to go ahead and say this was completed in my original implementation of the source data. 
Thanks. 
Cheers!

**Comment by mateonnelson** [comment]
James, don’t bill us for that answer….
