### ISSUE TITLE
Existing Supplies Theme - WUG Points

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#194]
![161201_existingsupplywugpointexample](https://cloud.githubusercontent.com/assets/23641348/20813867/f486bca0-b7dc-11e6-8605-55b3d4706489.JPG)
When a user selects the Existing Supplies theme for any of the data types (County, Water User Group, Usage Type, Regional Water Planning Area), the color of the dot that represents the water user groups (WUGs) is almost the same color as the surface water sources. We suggest you use a different color for the WUGs in this view to help distinguish the dots from the other graphics in the map.

**Comment by adambreznicky** [comment]
what color would you like? i'm thinking a lighter red or pink...

**Comment by SabrinaAnderson** [comment]
Matt suggested a gray color, but light pink or red would help it stand out better. We default to you as to what you think would work best since the dots coordinate with the chart data. If we cannot find a suitable color, then the current color will have to work.

**Comment by adambreznicky** [comment]
the gray didn't stand out nearly enough in front of the gray-toned basemap so i tried the pink but it didn't have enough contrast to the purple demand color in the statistical charts. i ended up just swapping the purple demand color and the blue existing supplies color since no sources are displayed when the selected theme is 'demand'.

**Comment by adambreznicky** [comment]
after discussion with Matt and realizing the colors were tied to the water plan publication, i reverted all colors back to their original color. i then changed only the existing supplies - in the map only - to gray.
