### ISSUE TITLE
Request for Map to Retain Placement & Scale when Switching Between Themes

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#195]
When a user zooms in or pans to a location on the 'Data by Planning Decade and Theme' map and then they select another theme like population, demands, or existing supplies, the map resets itself to the original scale/placement. It would be helpful to have it retain how the user has zoomed in on the map so that when they are comparing two different themes, they do not have to zoom/pan again.

**Comment by adambreznicky** [comment]
this functionality is offered to the user with the 'lock' button. 
:)

**Comment by SabrinaAnderson** [comment]
Yep, that one was the most common application issue, the "user" issue.
