### ISSUE TITLE
Existing Supplies and Strategy Supplies Zero Display

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#196]
Adam and I already spoke about this bug. I'm just adding it for documentation purposes.

In the existing supply and strategy supply themes, when a decade is chosen and the supply value associated with it is zero, but not all decades associated with the supply view's record have values of zero, the related data in the Raw Data table should not display and the associated Water User Group (Entity) and source showing zero supply should also not display. Only when the Entity has zero supply for the source in all decades should that zero value display in the Raw Data table and in the interactive map.

**Comment by adambreznicky** [comment]
thanks for putting this on here for documentation.
i have already fixed this issue in my working copy and will be part of the next push.

**Comment by SabrinaAnderson** [comment]
Thank you for updating it. We'll check this during the next round of testing.
