### ISSUE TITLE
Planning Region / County Data Type Outline

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#197]
When the user selects a data type of Planning Region or County, the map displays these boundaries using a dark blue outline. When the user clicks on the Existing Supplies or Strategy Supplies themes, the dark blue outline is no longer visible when aquifers are displayed because they too are dark blue. We suggest that the boundary of the data type chosen be updated to a contrasting color to help the user still see the area of interest along with the sources it relies upon.

**Comment by adambreznicky** [comment]
can you suggest an alternative color? i think this blue was chosen to align with the blues picked for the banners and the general color palette of the app; i can only assume communications had something to do with this as it is my understanding they chose specifics fonts and such. 

pick a color and i can change it.
right now the boundary color matches the map at the top of the page for consistency to the user. do you only want it different in the lower theme map, or both the top and the bottom?
do you only want it different when the chosen theme is existing or strategy supplies?... or all themes in the lower map?

**Comment by SabrinaAnderson** [comment]
As we discussed, we just need a color to help the selected data type stand out better, Matt had suggested a muted yellow (nothing to bright), but if you have a better suggestion, please give it a try and we'll see how it looks. The boundary color chosen should be consistent across all themes and in the banner map if possible.

**Comment by adambreznicky** [comment]
i went with a dark/burnt orange since it contrasted most of the various entity colors well. i did have to lighten up the population color though to be a brighter yellow.

**Comment by adambreznicky** [comment]
i had reverted the population yellow back to it's original orange. Matt said that the publication color for population was more important and that the contrast was fine.
