### ISSUE TITLE
WUG with No Strategy Supplies Interactive Map Display Issue

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#198]
![161201_aguadulcenostrategysuppliesmapview](https://cloud.githubusercontent.com/assets/23641348/20813813/c0d9c9d8-b7dc-11e6-814f-1731c66f0ab3.JPG)
The water user group entity named Agua Dulce does not have any strategy supplies associated with it. When the user selects a data type of Water User Group and selects 'Agua Dulce' then scrolls down to the Data by Planning Decade and Theme map and selects the them Strategy Supplies, the point for Agua Dulce does not display in the map. This is expected because the point will only display when a strategy supply record is associated with the selected WUG. However, I noticed that the 'Potential Shortage' legend still displays when going directly from 'Needs' to 'Strategy Supplies' and that could be confusing to the user. If the user goes from another theme to the 'Strategy Supplies' theme this does not occur.

**Comment by adambreznicky** [comment]
moved legend control removal code to run before the escape functionality primed for when no wug features exist. fixed.
