### ISSUE TITLE
WUG with no Existing Supplies Missing Message

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#199]
![161201_s-eandersonnoexistingsuppliesmapview](https://cloud.githubusercontent.com/assets/23641348/20813786/a285c5cc-b7dc-11e6-857e-acd1ebfc83fa.JPG)

The water user group, Steam Electric Power, Anderson does not have an existing supply record associated with it. When the user selects the data type Water User Group and selects the value 'Steam Electric Power, Anderson', when the user selects the 'Existing Supplies' theme in the Data by Planning Decade and Theme map the map also displays the Potential Shortage key box. Also, unlike with the strategy supplies, there is not a message displayed beneath the map that explains to the user that there are no existing supplies related to the WUG. I see the message in the Download Data section, but the user must scroll down to see it. Is there a way that on both the Existing Supplies and the Strategy supplies themes, that if no records display in the Raw Data section, a message displays where the table data should be listed explaining no supplies is related to the WUG for that theme?

**Comment by adambreznicky** [comment]
created message to appear (for every theme) instead of the table if no data exists.
