### ISSUE TITLE
SVG icons for water use types

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#20]
@christoball - when you get a chance (probably after the Forum), could you create SVGs for the water use categories like you had in the 2012 water plan mock-up a couple years ago?

**Comment by christoball** [comment]
@jseppi take a look
![waterplanicon-mock](https://cloud.githubusercontent.com/assets/1877550/12457187/dc00e768-bf68-11e5-8aeb-0402b792284e.jpg)

**Comment by jseppi** [comment]
- Make chart headings body text color (instead of blue)
- Try 1px chart heading underline
- Add CC attribution for factory icon to About page

**Comment by christoball** [comment]
Credit text:
Manufacturing icon created by Jeremy J Bristol for the [Noun Project](https://thenounproject.com/)

Files:
[water-plan-icons.zip](https://github.com/TNRIS/iswp2017/files/97854/water-plan-icons.zip)

**Comment by jseppi** [comment]
:+1: thanks!

**Comment by jseppi** [comment]
@christoball - Can you concoct a mining icon with a pickaxe and rubble per @mateonnelson's emailed comments?

**Comment by jseppi** [comment]
And here's a public domain cow with it's head up, more similar to the mock-up one: 
![noun_12541](https://cloud.githubusercontent.com/assets/697848/12458413/7283d5d2-bf6f-11e5-923f-f4dd2511a6a5.png)

(https://thenounproject.com/search/?q=cow&i=12541)

**Comment by christoball** [comment]
The other mining icon was public domain, so we can revert to that, but wondering doesn't the pickaxe exclude the oil and gas aspect of 'mining'?

**Comment by jseppi** [comment]
Yeah, I agree but @mateonnelson says:

> I think old mining is clearer since it includes all natural resource extraction activities from actual coal to uranium to gravel and sand.

**Comment by christoball** [comment]
How does this one look? 

![image](https://cloud.githubusercontent.com/assets/1877550/12462640/06df8ca2-bf85-11e5-9973-5af01d99c2f1.png)

**Comment by jseppi** [comment]
I think that looks great

**Comment by christoball** [comment]
@jseppi Just one file but github made me zip it.
[drill_rubble_icon-01.zip](https://github.com/TNRIS/iswp2017/files/98077/drill_rubble_icon-01.zip)

**Comment by mateonnelson** [comment]
Groovy
Thx

.

On Jan 20, 2016, at 14:50, Chris <notifications@github.com<mailto:notifications@github.com>> wrote:


How does this one look?

[image]<https://cloud.githubusercontent.com/assets/1877550/12462640/06df8ca2-bf85-11e5-9973-5af01d99c2f1.png>

-
