### ISSUE TITLE
Change to default MAP VIEW

### ISSUE THREAD

**Issue by mateonnelson** [TNRIS/iswp2017#201]
Adam,
I am thinking that the default data view of the bottom map should now be changed from ‘needs’ to ‘strategy supplies’ now that we are mapping the sources which is the much more interesting view.
 
Thanks
m

**Comment by adambreznicky** [comment]
i have changed the views to default to strategy supplies. in doing so, this caused a fatal error on several entity & source pages which do not have associated strategies. this error was the same as the specific 'jasper county - 2020 - strategy supplies' error which i had brought up previously via email. so naturally, this change justified troubleshooting this outstanding error (woohoo!!). 

i have successfully changed this default as requested and fixed the associated fatal error.
