### ISSUE TITLE
theme map displays entites with valuesum = 0

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/iswp2017#202]
the theme map displays all entities regardless of their value for the chosen decade. is this correct? should the entities be filtered to only display when non-zero values are present for the selected theme/decade criteria? or filter the same as the sources are, utilizing the DisplayZero field?
@mateonnelson @SabrinaAnderson

**Comment by SabrinaAnderson** [comment]
Did you get an answer from Matt on this question? I would think that they should behave the same as sources and only display in the map when they have a value greater than zero, but display in the table if all decades are zero (updated source rule).

**Comment by adambreznicky** [comment]
I never heard from Matt about this. i would agree with your thinking about not showing in the map unless they have a value, but always showing in the table as long as they are related.
discuss with matt and let me know what y'all decide.

**Comment by adambreznicky** [comment]
implemented with commit c1fcd4bcd51ac60edc92e561717fd35e21a6bff9
now hosted in the staging environment for review and verification we want to keep this functionality

**Comment by SabrinaAnderson** [comment]
I've tested the entity value sum = 0 display and it appears to be working as we discussed.
