### ISSUE TITLE
projects!

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/iswp2017#204]
~~1.) add project points to theme map for strategy supplies theme~~

- change shape and/or color of mapped project points?
- add additional/alternative fields to project point popup?
- add legend to strategies theme map to identify project vs entity points?

 @mateonnelson @sabrinaanderson: these questions are derivative of having completed number 1 and pertain to various small details & aesthetics. what do you think?

~~2.) create a projects view~~
- add link to in project point popups to the project view for that project

**Comment by adambreznicky** [comment]
as per commit c130667c07232ace97a655c4bab408e65709127d and currently displayed in the staging environment for review:

- kept triangle shape. changed color to red with white border
-did not add legend, instead added a footnote to the map identifying what the triangles represent as per @mateonnelson direction via email

**Comment by SabrinaAnderson** [comment]
On the title of the interactive map display, I have on my marked up copy from Matt that the title should display as Water User Groups - 2020 - Population Benefiting. Right now it's missing the 'Population Benefiting.'
![projectview-interactivemaptitle](https://cloud.githubusercontent.com/assets/23641348/21940599/b26e6186-d98a-11e6-9476-65b1a17fa6dd.JPG)

**Comment by adambreznicky** [comment]
![20170113_124429](https://cloud.githubusercontent.com/assets/5650145/21941388/2824de84-d98e-11e6-9dd9-7fffd7a1b4e5.jpg)

my markup has the 'Population Benefiting' but then it's crossed out... as if to say Matt changed his mind between the two markups. 
It still remains on the chart on mine though.
Can you confirm if he does or does not want that piece of the title over the map? Its a super quick fix so no biggie.

**Comment by SabrinaAnderson** [comment]
He may have forgotten that we are not displaying the total population of the WUG in the map, just the total population of the WUG splits that are benefiting from the project. I'll check to make sure that I understood his wishes.

**Comment by SabrinaAnderson** [comment]
Matt agreed with the map title change. Update it whenever convenient. I've just notified the other testers that the project summary view is up and running in staging.

**Comment by adambreznicky** [comment]
deployed to production in issue #225
