### ISSUE TITLE
Source page heading spelling of 'Groundwater'

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#206]
![161215_groundwaterinheading](https://cloud.githubusercontent.com/assets/23641348/21242810/abeba5be-c2db-11e6-869d-07e3be6172e6.JPG)

Under the aquifer name it lists 'Ground water Source in' and it should read 'Groundwater Source in'.

**Comment by adambreznicky** [comment]
fixed in commit a91a1bccf0fd8213910023358fc7d4a6fe39f124
