### ISSUE TITLE
proposed/future reservoirs need to map as a different shade of blue

### ISSUE THREAD

**Issue by mateonnelson** [TNRIS/iswp2017#208]
Marvin Nichols reservoir, for example, should be a different blue shade.  
right now, it maps with same color as existing reservoirs.
per:
https://2017-staging.texasstatewaterplan.org/region/C

The link to this 2012 data view shows the two types of shades we should use.
http://2012.texasstatewaterplan.org/#/strategies/2010/region/C

doing so keeps folks from getting confused about what exists already.
thanks
m

**Comment by adambreznicky** [comment]
resolved commit db68d86118489a8f3e634287b15ed2efc66a41fd
