### ISSUE TITLE
we now have regional summaries that should also be referenced on the 16 region pages

### ISSUE THREAD

**Issue by mateonnelson** [TNRIS/iswp2017#210]
Please modify the regional summary paragraphs, for example, the one located at
https://2017-staging.texasstatewaterplan.org/region/G    as follows:

1)  add the word "full" in the last (existing) sentence as follows:
"blah.....The **full** 2016 Brazos (G) Regional Water Plan can be found on the TWDB Web site at http://www.twdb.texas.gov/waterplanning/rwp/plans/2016/#region-g"

2) add another sentence at the end of that paragraph that reads: 
"A summary of the 2016 [Brazos G] Regional Water Plan can be found at
http://www.twdb.texas.gov/waterplanning/swp/2017/doc/2016_RegionalSummary_G.pdf"

I don't think you'll need this but the overall link to all these summaries is located at the bottom of:
http://www.twdb.texas.gov/waterplanning/swp/2017/index.asp

**Comment by adambreznicky** [comment]
resolved commit db68d86118489a8f3e634287b15ed2efc66a41fd
