### ISSUE TITLE
Project Display in Data Type Region View

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#217]
I spoke with Matt this morning and received confirmation on how we would like to see the projects displayed in the region view. 
Some background to help you understand where I will be going with this: a project will have just one Project Sponsor Region associated with it. This is the region that is responsible for including the project in the plan and the region associated with the main project sponsor who is responsible for acquiring the capital cost to build the project. If the project is built, it will benefit one or more water user groups that are located within the Project Sponsor Region and the project will sometimes benefit WUGs located in another region. The region that benefits from the project is the WUGRegion.

Currently, in the Planning Region view we are displaying projects in the Recommended Projects table and the interactive map based on the map.vw2017MapWMSProjects.WMSProjectSponsorRegion. We would like for the Recommended Projects table to be based on the WMSProjectSponsorRegion and the map to display projects based on the WUGRegion so that the region view interactive map displays only the projects that benefit the region. I was not totally thinking that through when designing the views for the project display. I was thinking that the map should represent what was included in the recommended list, but in order to remain consistent with other views, we need to display in the map based on WUG project beneficiaries.

If we are to update the map to display the data this way, you need both the wmsProjectSponsorRegion and the WUGRegion in the view. Would it be easiest for you if I were to just update the existing view named map.vw2017MapWMSProjects to include the WUGRegion field? This would cause the number of records to increase if a project is associated with more than one WUG beneficiary region. You could then select the data to display based on a distinct list of WMSProjectSponsorRegion for the Recommended Projects list and select the data by the WUGRegion field for the map display. 

Also, we need to update the map footer to display the text ‘Red triangles indicate capital projects associated with strategies supplies that have been assigned to a Water User Group.’ There are certain projects that will display in the Recommended Project list associated with the region, that do not have water management strategy supply assigned to a Water User Group(Example: GBRA’s Integrated Water-Power Project’) and we do not want them to display those projects in the map. Projects like these will have a NULL WUGRegion value.

Please let me know if this solution works for you.

**Comment by adambreznicky** [comment]
resolved in commit 19576d18d8622c59c54a5b19c2dfa32dffdc7c5c
