### ISSUE TITLE
Project View - WUG Population Display Prior to Project Online Decade

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#219]
Matt asked if we could update the map/table data in the project view so that population and WUG map points do not display prior to their related project's online decade. 

I will update the view named 'map.vw2017MapWMSProjectByEntityWUGSplit' so that the population in decades prior to the project's online decade are updated to zero. 

Adam said that he could hide all WUG points in the map prior to the project coming online. The problem is that we will have multiple decades with zero data and no map features when the project has a future decade of 2040+.  

@mateonnelson are you okay with empty maps on all decades except for 2070 for projects like 'WUG INFRASTRUCTURE EXPANSION (GROUNDWATER) - OLD RIVER-WINFREE - PHASE 2'?

**Comment by adambreznicky** [comment]
Updated the project view theme map to hide all entity points before the project decade online. 
Completed on commit 59eae5
