### ISSUE TITLE
Project List Hyperlinked Project Names

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#220]
One more interactive linkage needs to be made within the existing pages.
The projects listed in the tables on the following pages: region, county, entity, usage type, source (see also issue #221)  need to be hyperlinked to bring up their corresponding project pages so folks can go straight to those individual projects from the tables.
 ![170120projectlisthyperlinkedname](https://cloud.githubusercontent.com/assets/23641348/22150868/056db02a-dee1-11e6-8903-3e3c08415b79.JPG)

**Comment by adambreznicky** [comment]
added hyperlinks to all recommended projects tables via commit 5ef3cb30636dbaf4091df4717856aef9f8e79223
*note: usage type view does not display this table as it is simply too much data
