### ISSUE TITLE
Water Source - Related Project List not Shown

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#221]
In order to be consistent with the other pages that have the recommended related project lists, I think the list should also display on the source page. Y'all may have decided to not include it for a reason when discussing how that page should look, so please ignore if this issue if it has already been discussed.

**Comment by adambreznicky** [comment]
matt never indicated he wanted the table on this view but i don't think it really hurts although there may be several times that it is an empty table. i just went ahead and added the table. if matt doesn't like it i can remove it.
added via commit 5ef3cb30636dbaf4091df4717856aef9f8e79223
