### ISSUE TITLE
Updated iSWP Project Map Note Text

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#223]
While reviewing the project coordinates, we noticed a map note that needs to change since the project page will include projects that have not been assigned to WUGs. The page it is located on is https://2017-staging.texasstatewaterplan.org/project/

The updated text is:
Red triangles indicate capital projects. If a water user group does not display with the selected project, the project is not currently assigned to a specific water user group.

**Comment by adambreznicky** [comment]
the link you supplied returns a 404 error; it needs a project id at the end of it. could you pass along another link example and help identify exactly where the text is that you're referring to?
thanks

**Comment by adambreznicky** [comment]
nevermind. i found it. updated commit 8d05967b1c873a014c6604ce6773ec718b4eecfe
![selection_037](https://cloud.githubusercontent.com/assets/5650145/24409919/43462b76-1397-11e7-97a4-2f3b95888ab0.png)

**Comment by SabrinaAnderson** [comment]
Sorry about the error message. I just got back from a meeting and saw the emails. The image you listed  above is from the Water User Group page and that map note should stay as it was. It is only the project page's map note that needs to be updated. 

Here is a link to one of the project pages: [https://2017-staging.texasstatewaterplan.org/project/2110]

![wmsprojectnoterequiringupdatedtext](https://cloud.githubusercontent.com/assets/23641348/24414284/8d5a3eda-13a3-11e7-854e-866303172b28.JPG)

The updated text for that map note is:
Red triangles indicate capital projects. If a water user group does not display with the selected project, the project is not currently assigned to a specific water user group.

**Comment by adambreznicky** [comment]
right on. fixed.
