### ISSUE TITLE
iSWP About Page Update

### ISSUE THREAD

**Issue by SabrinaAnderson** [TNRIS/iswp2017#224]
Between the sections, 3) State Water Plan Data and 4) Glossary, we would like to add a new section on the page https://2017-staging.texasstatewaterplan.org/about that explains how the project locations were determined. The text that Sarah Backhouse provided for the section is listed below.

##How are the locations of the projects determined?
Water “projects” are the future capital investments in infrastructure that support water management strategies. Capital project symbols (red triangles) are mapped to a single point as a necessary simplification to represent a geographic location of each water project (e.g., well fields, reservoirs, pipelines) solely for the purposes of representing the water plan visually. The basis for selecting each representative location varied depending on the regional water plan and particular type of infrastructure but, in general, the default project locations relate to:
•	approximate locations of at least one component of major infrastructure such as dams, water treatment plants, water intakes for pipelines, or well fields proposed in the plan; or 
•	the primary location of the water user group in which certain types of infrastructure would be located, such as some water treatment plants within a city or water conservation investments; or
•	the centroid of the county in which a project with dispersed infrastructure would be located, such as county-wide irrigation, mining, or manufacturing conservation projects, or
•	the centroid of a county-aquifer polygon for certain, generalized groundwater supply projects.
The actual locations and physical extent of recommended projects will vary and, in many instances such as pipelines, will encompass multiple geographic locations and facilities.

**Comment by adambreznicky** [comment]
completed commit f793a9ac2aa2b5c951ed246df63e298a607613e5
