### ISSUE TITLE
Project Refresh

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#225]
Changes in the tables have been completed updating project and entity coordinates.  We are ready for a refresh and to deploy to staging.

**Comment by DavidHickman** [comment]
Hi Laura, 

Adam just left town for the next ten days or so. We went ahead and updated the data and deployed to the [staging site](https://2017-staging.texasstatewaterplan.org/project/1715). Let us know when you've had an opportunity to verify the updates and we can deploy to the production site.

Thanks!
David

@JasonKleinert

**Comment by lebell** [comment]
Hi David,

Thank you.  All the updates in staging look good to us.  Please deploy to the production site when you are able.

Thanks,
Laura

**Comment by DavidHickman** [comment]
The updates have been deployed to the production site. Let us know if we can do anything else to help!
