### ISSUE TITLE
New Water Management Strategy Type page

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#228]
#### Included on the page will be:
- The WMS type name 
- A written description of the WMS type 
- Recommended projects associated with the WMS type 
- A map of related strategies‘ sources and benefitting WUGs filtered by decade and the WMS type 
- A table showing the raw data of the strategy supplies associated with the WMS type that will include columns for WMS Type, Strategy, Source, Region, County, and Entity with hyperlink text as default.
- A hyperlink to download a csv of the data

## Mock Up Specifications

![wmstype_examplepage](https://user-images.githubusercontent.com/5649664/30288877-d95aa804-96ef-11e7-8b32-dc8e50647031.png)

### This section is intended to provide further detail regarding data and functionality specifications for each numbered update item on the graphic mockup.

__1. Add “WMS Type” as an option to the main ‘View data for’ drop down menu__
- __Function:__ When WMS Type is chosen a second drop down menu will appear with the list of types. Same functionality as existing menu items. 
- __Data:__ WMS Type, add to bottom of menu

__2. Add “Select WMS Type” as default text, and include drop down list of Water Management Strategy Type options__
- __Function:__ Display drop down menu of all WMS types for user to select. When user selects type, and presses the ‘GO’ button the page will update to display information about the selected WMS type. Same functionality as existing menu items.
- __Data:__ Select distinct WMSType from RWP.map.vw2017MapWMSWugSupply

__3. Water Management Strategy Type__
- __Function:__ Display WMS type name dynamically based on user chosen type throughout page.
- __Data:__ Select distinct WMSType from RWP.map.vw2017MapWMSWugSupply 

__4. Water Management Strategy type description__
- __Function:__ Display description corresponding with and updated based on WMS type.
- __Data:__ WMS Type Description from WMS_Type_List.xl

__5. Update heading to read “Recommended Projects related to Water Management Strategy Type”__
- __Function:__ Table will display all recommended projects associated with the user selected WMS type, and function the same way as on other pages.
- __Data:__ table data will be fed by RWP.map.vw2017MapWMSProjectsByWMSType

__6. Update section header to reflect planning decade as only variable__
- __Function:__ Strategy supplies will be the only theme for the map used on this page so the theme label and button functionality can be removed from this header section. The only variable the user should be able to update is the decade. The map will display the distinct projects by WMS Type, the related sources, and benefitting WUGs. All other functionality the same as on other pages.
- __Data:__ map data will be fed by RWP.map.vw2017MapWMSWugSupply and RWP.map.vw2017MapWMSProjectsByWMSType

__7. Update map title to include WMS Type, decade year being displayed dynamically, and strategy supplies as the only theme__
- __Function:__ Map will display the WUGs and recommend projects associated with the user selected WMS type. Similar functionality to interactive maps located on other pages, with one exception.  Please use flag column ‘DisplayProjectInMap’ in the RWP.map.vw2017MapWMSProjectByWMSType view to only display projects on the interactive map that have a ‘Y’ value.
- __Data:__ “Water Management Strategy Type – YYYY – Strategy Supplies (acre-feet/year)”

__8. Hyperlink to strategy page__
- __Function:__ Hyperlink text of WMS data to have same functionality as region and entity hyperlink text in raw data section. When the user clicks a WMS name the associated WMS Id will be the parameter that is passed through to navigate to that specific strategy page. EX: https://2017.texasstatewaterplan.org/WMS/<WMSId>
- __Data:__ RWP.map.vw2017MapWMSWugSupply

__9. Hyperlink to source page__
- __Function:__ Hyperlink text of source data to have same functionality as region and entity hyperlink text in raw data section. When the user clicks a source name the associated MapSourceId will be the parameter that is passed through to navigate to that specific water source page. EX: https://2017.texasstatewaterplan.org/source/<MapSourceId>
- __Data:__ RWP.map.vw2017MapWMSWugSupply

__10. Add drop down filter column for WMS Type__
- __Function:__ Display drop down filter box for WMS Type data as first column in Raw Data section. Same functionality as other column filter headings in Raw Data section.
- __Data:__ WMS Type

**Comment by lebell** [comment]
Adding the WMS_Type_List.xlsx which lists the WMS types and descriptions.
[WMS_Type_List.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c00795e2fc2f00116e3138/125516c66e82c728ace21e0d46dfb9a91cb69ab98ad6934ab749b2d86b56357c2301a03f32dfa17de6402d580c5846a9170a5b4cf9f9892eaebe6e77db0f0cffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98a49c7ee3c23e58d8f4b390c48.xlsx)

**Comment by lebell** [comment]
Whenever the application hyperlinks to the 'Drought Management' WMS type the link fails. We think this is caused by drought management not being associated with a project. The view to use that will allow the associated WMS to display without having a project is map.vw2017MapWMSWUGSupply. The view vw2017MapWMSProjectsByWMSType should only be used when displaying the list of projects related to a WMS type or displaying projects in the map view that are related to the WMS type.

Please update the Recommended Projects related to Water Management Strategy Type table to display all related strategies including those listed as 'DisplayOnMap' = N

**Comment by lebell** [comment]
Works great, thank you! Please update to done.
