### ISSUE TITLE
New Water Management Strategy page

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#229]
#### Included on the page will be:
- The WMS name 
- The water management strategy sponsor region with a hyperlink to that region page
- Recommended projects associated with the WMS 
- A map of related strategies‘ sources and benefitting WUGs filtered by decade and the WMS 
- A table showing the raw data of the strategy supplies associated with the WMS that will include columns for Strategy, WMS Type, Source, Region, County, and Entity with hyperlink text as default.
- A hyperlink to download a csv of the data

## Mock Up Specifications

![wms_examplepage](https://user-images.githubusercontent.com/5649664/30288948-1c066b0c-96f0-11e7-86a7-c8ebac1ce989.PNG)

### This section is intended to provide further detail regarding data and functionality specifications for each numbered update item on the graphic mockup.

__1. Add “Water Management Strategy” to the drop down list__
- __Function:__ When Water Management Strategy is chosen a second search box will appear where the user may start typing to search for a specific strategy. Same functionality as existing menu items.
- __Data:__ Water Management Strategy, add below WMS Project

__2. Add “Find Water Management Strategy” as default text__
- __Function:__ Display search box of all WMS types for user to select with suggestions and auto complete. When user selects strategy, and presses the ‘GO’ button the page will update to display information about the selected WMS. Same functionality as existing menu items.
- __Data:__ WMS Name from RWP.map.vw2017MapWMSWugSupply

__3. Water Management Strategy name__
- __Function:__ Display WMS name dynamically based on user chosen WMS throughout page.
- __Data:__ WMS Name from RWP.map.vw2017MapWMSWugSupply

__4. Hyperlinked WMS sponsor region__
- __Function:__ Display the WMS sponsor region dynamically with hyperlink to region page.
- __Data:__ Sponsor Region from RWP.map.vw2017MapWMSWugSupply

__5. Update heading to read “Recommended Projects related to Water Management Strategy”__
- __Function:__ Table will display all recommended projects associated with the user selected WMS, and function the same way as on other pages.
- __Data:__ table data will be fed by RWP.map.vw2017MapWMSProjectByWMS

__6. Update section header to reflect planning decade as only variable__
- __Function:__ Strategy supplies will be the only theme for the map used on this page so the theme label and button functionality can be removed from this header section. The only variable the user should be able to update is the decade. The map will display the distinct projects by WMS, the related sources, and benefitting WUGs. All other functionality the same as on other pages.
- __Data:__ map data will be fed by RWP.map.vw2017MapWMSWugSupply and RWP.map.vw2017MapWMSProjectByWMS

__7. Update map title to include Water Management Strategy, decade year being displayed dynamically, and Strategy Supplies as the only theme__
- __Function:__ Map will display the WUGs and recommend projects associated with the user selected WMS. Similar functionality to interactive maps located on other pages, with one exception.  Please use flag column ‘DisplayProjectInMap’ in the RWP.map.vw2017MapWMSProjectByWMS view to only display projects on the map that have a ‘Y’ value.
- __Data:__ “Water Management Strategy – YYYY – Strategy Supplies (acre-feet/year)”

__8. Add drop down filter column for WMS Type__
- __Function:__ Display drop down filter box for WMS Type data as the second column in Raw Data section. Same functionality as other column filter headings in Raw Data section.
- __Data:__ WMS Type

__9. Hyperlink to WMS Type page__
- __Function:__ Hyperlink text of WMS type data to have same functionality as other hyperlink text in raw data section. When the user clicks a WMS type this will be the parameter that is passed through to navigate to that specific water source page. EX: https://2017.texasstatewaterplan.org/wmstype/<wmstype>
- __Data:__ RWP.map.vw2017MapWMSWugSupply

__10. Hyperlink to Source page__
- __Function:__ Hyperlink text of source type data to have same functionality as region and entity hyperlink text in raw data section. When the user clicks a source name the associated MapSourceId will be the parameter that is passed through to navigate to that specific water source page. EX: https://2017.texasstatewaterplan.org/source/<SourceId>
- __Data:__ RWP.map.vw2017MapWMSWugSupply

**Comment by lebell** [comment]
- Item 2 (default text in the search bar) - This was exactly what we requested, but could we please change this to read "Find WMS" as the default text instead so that it does not get cut off?

- Item 4 (hyperlinked WMS sponsor region) - For consistency with the other pages please update the text to all be italicized with only the region letter hyperlinked.

- Item 5 (Recommended Projects related to Water Management Strategy table) - Please update table to display all related strategies including those listed as 'DisplayOnMap' = N

- Item 7 (heading for map section) - This was what we requested, but we realized this should read "**Water User Groups** - 2020 - Strategy Supplies (acre-feet/year)" instead of "Water Management Strategy - 2020 - Strategy Supplies(acre-feet/year)"

**Comment by JasonKleinert** [comment]
Completed bullets 1,2,4 above, still need to complete bullet 3.

**Comment by DavidHickman** [comment]
@lebell - In the current production app, the link to a region page includes "Region" if the link is in the page summary, e.g. [Andrews County](https://2017.texasstatewaterplan.org/county/Andrews): "County in [Region F](https://2017.texasstatewaterplan.org/region/F)"

Should these links also be the region letter only, or stay the same as current production? (Item 4 above)

> Item 4 (hyperlinked WMS sponsor region) - For consistency with the other pages please update the text to all be italicized with only the region letter hyperlinked.

**Comment by lebell** [comment]
My mistake, please keep it consistent with the county page and include "Region" in the hyperlink. Thank you for catching that!

**Comment by DavidHickman** [comment]
Awesome! Thanks for the clarification!

**Comment by lebell** [comment]
Looks great, thank you! Please update to done.
