### ISSUE TITLE
Revisit existing pages and update the Raw Data table text to include hyperlinks that connect with all other pages

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#231]
__Hyperlink to strategy page__
- __Function:__ Hyperlink text of WMS data to have same functionality as region and entity hyperlink text in raw data section. When the user clicks a WMS name the associated WMS Id will be the parameter that is passed through to navigate to that specific strategy page. EX: https://2017.texasstatewaterplan.org/WMS/<WMSId>
- __Data:__ RWP.map.vw2017MapWMSWugSupply

__Hyperlink to Source page__
- __Function:__ Hyperlink text of source data to have same functionality as region and entity hyperlink text in raw data section. When the user clicks a source name, the associated MapSourceId will be the parameter that is passed through to navigate to that specific water source page. EX: https://2017.texasstatewaterplan.org/source/<SourceId>
- __Data:__ RWP.map.vw2017MapWMSWugSupply

Pages that will need to be updated to include hyperlinks to water management strategies and sources:
- Planning Region - https://2017.texasstatewaterplan.org/region/<RegionLetter>
- County - https://2017.texasstatewaterplan.org/county/<CountyName>
- Water User Group - https://2017.texasstatewaterplan.org/entity/<EntityId>
- Usage Type - https://2017.texasstatewaterplan.org/usagetype/<UsageType>
- Water Source - https://2017.texasstatewaterplan.org/source/<MapSourceId>

**Comment by lebell** [comment]
Thank you! Looks good, please mark as done.
