### ISSUE TITLE
Update map section header

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#232]
Update map section header to reflect planning decade as only variable on WMS Project page, and remove Strategy Supplies theme button.

![image](https://user-images.githubusercontent.com/5649664/30286483-56266e6c-96e7-11e7-87ef-8f047a50dadf.png)

**Comment by JasonKleinert** [comment]
Ready for review at : https://2017-staging.texasstatewaterplan.org/statewide

**Comment by lebell** [comment]
Looks good to us!
