### ISSUE TITLE
Add section to Projects page of recommended strategies related to the selected project and the WMS sponsor region

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#233]
Add section to Projects page of recommended strategies related to the selected project and the WMS sponsor region. The WMS name information in the table should be hyperlink text to the associated WMS page and the WMS sponsor region should be hyperlink text to the associated region page. Please include a disclaimer at the bottom that reads:
>“Only strategy names that have strategy supplies assigned to a Water User Group are linked to a water management strategy page.”

__Hyperlink to strategy page__
- __Function:__ Hyperlink text of WMS data to have same functionality as region and entity hyperlink text in raw data section. When the user clicks a WMS name the associated WMS Id will be the parameter that is passed through to navigate to that specific strategy page. EX: https://2017.texasstatewaterplan.org/WMS/<WMSId>. WMS name should act as the filter component in this table when there are multiple records. Strategies with water volumes not fully allocated to WUGs will not have strategy page hyperlinks.
- __Data:__ RWP.map.vwMap2017WMSProjectbyWMS

__Hyperlink to region page__
- __Function:__ Hyperlink text of sponsor region data to have same functionality as hyperlink text in raw data section. When the user clicks a region letter the associated region letter will be the parameter that is passed through to navigate to that specific region page. EX: https://2017.texasstatewaterplan.org/region/<RegionLetter>. 
- __Data:__ RWP.map.vwMap2017WMSProjectbyWMS

![image](https://user-images.githubusercontent.com/5649664/30286388-0ff1f0b0-96e7-11e7-9e14-363645e234ec.png)

**Comment by lebell** [comment]
Looks good, thank you! Please mark as done.
