### ISSUE TITLE
Correct all map disclaimer text

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#235]
Correct all map disclaimer text from:
>“Red triangles indicate capital projects associated with strategies supplies that have been assigned to a Water User Group” 

to be:

>“Red triangles indicate capital projects associated with strategy supplies that have been assigned to a Water User Group.” 

Appears on the following pages:
- Planning Region - https://2017.texasstatewaterplan.org/region/<RegionLetter>
- County - https://2017.texasstatewaterplan.org/county/<CountyName>
- Water User Group - https://2017.texasstatewaterplan.org/entity/<EntityId>
- Usage Type - https://2017.texasstatewaterplan.org/usagetype/<UsageType>
- Water Source - https://2017.texasstatewaterplan.org/source/<MapSourceId>

**Comment by JasonKleinert** [comment]
Ready for review at : https://2017-staging.texasstatewaterplan.org/statewide

**Comment by lebell** [comment]
Reviewed and looks good to us- thank you!
