### ISSUE TITLE
Update map on Source page to use the new flag column ‘DisplayProjectInMap’

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#236]
Update map on Source page to use the new flag column ‘DisplayProjectInMap’ from the RWP.map.vw2017MapWMSProjectBySource to only display projects with a value of ‘Y’ on the map.
This flag will only be used when displaying projects in the interactive map. The section titled “Recommended Projects Associated with a Source” will still display the complete distinct list of projects associated with the source. This change will allow projects like the Region L Integrated Water-Power Project to be listed as a recommended project associated with the source without displaying it in the map since the map only represents projects associated with assigned recommended water user group supplies. The Integrated Water-Power Project is recommended and related to the Gulf of Mexico Source, but its associated strategy supply is not assigned to a specific water user group.

**Comment by lebell** [comment]
Looks good, thank you! Please mark as done.
