### ISSUE TITLE
Update the Download Data section to display links consistently across all application pages

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#237]
Update the Download Data section to display links consistently across all application pages. Some pages display all links automatically and some pages display links based on the theme button selection. Our preference would be to display all download links at the bottom of each page without the need to select theme buttons. The following pages rely on theme button selection to control data download link display:
Home Page - https://2017.texasstatewaterplan.org/statewide
Planning Region - https://2017.texasstatewaterplan.org/region/<RegionLetter>
County - https://2017.texasstatewaterplan.org/county/<CountyName>
Usage Type - https://2017.texasstatewaterplan.org/usagetype/<UsageType>

**Comment by JasonKleinert** [comment]
Ready for review at : https://2017-staging.texasstatewaterplan.org/statewide

**Comment by lebell** [comment]
Reviewed and looks good to us- thank you!
