### ISSUE TITLE
Add a ‘How do I use the interactive map?’ section to the About page

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#238]
### Add a ‘How do I use the interactive map?’ section to the About page that will include the following text and image:
>Interactive maps are included to view and explore the state water plan data geographically. Here are some tools that will help you navigate and use the maps:
>- Pan – To move the map; click and hold the left mouse button and drag the map to a new place.
>- Zoom – To see more details or a larger area on the map you can zoom in and out using the +/- sign buttons in the top right. Double left clicking your mouse on a map area will also zoom you into that location. 
>- Statewide View – To quickly view all of Texas click on the button in the upper right with the Texas graphic.
>- Lock Extent – To freeze the map at a specific location and zoom level click the lock button on the right side of the screen.  The button will darken when turned on and lock the map extent as you click through the different theme and decade buttons. 
>- Map Information – Symbol descriptions, notes, and disclaimers may appear just below the map panel to provide more information about what is being displayed.
>- Hover Labels – Some map items will display labels when you hover your mouse over them. Clicking on any of these items will navigate you away from the current page to a page related to that item in the interactive state water plan.
>- Decade Buttons – These are in the banner above the map and filter the map data by decade. For example, Project symbols will begin displaying on the map in the decade that matches the project’s online decade and continue to show in all subsequent decades.
>- Theme Buttons – These are in the banner above the map and filter the map data by type.
>- Symbol Popups – You can click on individual symbols to open a popup displaying data associated with that item. If there are overlapping symbols clicking on the cluster will cause them to spread out and allow you to select each one individually.

>![image](https://user-images.githubusercontent.com/5649664/30285548-0d17dca4-96e4-11e7-99f1-d3fd521c28e1.png)

>Due to the nature of the state water plan data not everything is relevant to display on the map. Please keep the following in mind when exploring the interactive maps:
>- The map for a selected region page will only display projects that benefit water user group splits within that planning region.
>- Sources will only display in the map if at least one water user group has an existing supply or water management strategy supply amount greater than zero tied to it in the selected decade.
>- Only the following sources are mapped: groundwater, indirect reuse, reservoir, system, run-of-river, and seawater.
>- If a water user group is related to a zero value for a specific theme and decade it will not display on the map, except for WUGs with zero associated population on the project page. For example, the needs map theme will not display a WUG point if they have zero needs in the selected decade.
>- If the water management strategy water supplies for a project are not assigned to a specific water user group, then the project will not display on the map.  For example, the Region L project called “Integrated Water-Power Project” will display in the list because it is a recommended project, but it does not have any WUGs associated with its strategy supplies so it will not display in the map.

**Comment by JasonKleinert** [comment]
Ready for review at : https://2017-staging.texasstatewaterplan.org/statewide

**Comment by lebell** [comment]
Could you please add a semi colon after "Pan – To move the map", and update the graphic with the attached updated one so it reflects the corrected disclaimer text from issue #235.
![MapGuide.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c00795e2fc2f00116e3138/125516c66e82c728ace21e0d46c5958a04978aad8aabf301b44fff9e2c4533317346f67272d3ba2be81a2e070d5b46a941585a4cf4ab8e7af5b12e6c981e5ab38532022d8c6853beb2901eb60bbb258b4887b7be8b4bc1e03527f5c6.png)

**Comment by lebell** [comment]
Looks good, thank you! Please mark as done.
