### ISSUE TITLE
Fix the broken hyperlink in the glossary section

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/iswp2017#240]
Fix the broken hyperlink in the glossary section to link to the following url: http://www.twdb.texas.gov/waterplanning/swp/2017/chapters/10-SWP17-GLOSSARY-APPENDICES.pdf?d=3717.1800000000003

**Comment by JasonKleinert** [comment]
Ready for review at : https://2017-staging.texasstatewaterplan.org/statewide

**Comment by lebell** [comment]
Reviewed and looks good to us- thank you!
