### ISSUE TITLE
Update background URL

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#244]
Update URL for background texture from subtlepatterns.com to  https://www.toptal.com/designers/subtlepatterns/. Is this possible to complete by October 26th? The old URL may close on that day. Please see below email for reference. 

 Hello,
 My name is Michelle Young and I work for a company called Toptal. 
 Your site cites the following tool subtlepatterns.com on a number of your pages, including: 
 https://2017.texasstatewaterplan.org/about
 Toptal recently acquired this tool. In the process, we've added a number of key improvements to help it run faster and be more streamlined with browsers. 
 The tool's location has been updated to the following URL: 
 https://www.toptal.com/designers/subtlepatterns/
 Please update the hyperlink on your website to this updated URL. 
 We will close out the old URL in 90 days. If you would like assistance with updating these hyperlinks, I am happy to help by providing a list of all their locations. 
 
Kind Regards,
Michelle

**Comment by JasonKleinert** [comment]
I think we should be able to make this change and redeploy to production before the 26th. I'll look into it and let you all know what we can do.

**Comment by JasonKleinert** [comment]
I updated the reference to the correct url in the code, the background file is already static, so no need to redeploy. This one is closed.

**Comment by lebell** [comment]
Thank you!

**Comment by lebell** [comment]
Good morning,

I hope the Forum went well! Could you please double check this update when you have time? It’s still coming up as the old url when we check it.

[cid:image001.png@01D35165.E8EC66B0]

Thank you,
Laura

**Comment by JasonKleinert** [comment]
Previously, I checked the reference to this texture throughout the app and we are referencing a local file, so nothing will break except the link in the about page if they move that old url. I have updated that link in about and it will be updated with the next push to production.

**Comment by lebell** [comment]
Looks good, thank you! Please mark as done.
