### ISSUE TITLE
Harmonize database schema

### ISSUE THREAD

**Issue by DavidHickman** [TNRIS/iswp2017#246]
Hi @lebell !

@JasonKleinert  and I are getting close to releasing the new WMS view to staging for review. One issue that we've encountered is small inconsistencies in the database schema.

_For example:_ W**ms**ProjectId **_vs._** W**MS**ProjectId

This seems to occur in several tables/fields, but primarily with WMS/Wms. Would it be possible to make these all consistent? We can make exceptions in the app code for each variance, but schema reconciliation is probably the better long-term solution. I'm not sure how many systems this data is tied to, so if a schema change isn't possible, we certainly understand.

Thanks!!

**Comment by SabrinaAnderson** [comment]
Yes, David we can make them consistent. We can update all instances of WMS to the fully capitalized form. Will making these changes to a field like 'WmsProjectSponsorRegion' impact any of the work that Adam did? Meaning, are there are any changes that we should avoid making because you've already made exceptions for them? The changes to the view's SQL code will be very simple and then we will need to submit the changes to IT which will take a day or two.

**Comment by DavidHickman** [comment]
Hi Sabrina, 

That would be a great solution for our purposes. It may require some small changes to the app code to remove a few exceptions, but I think making that change will reduce extraneous code in the long-term.

Thank you for making those adjustments! Let us know when the changes have gone through and we'll pull a fresh copy of the data. We have other enhancements we can continue working on, so there's no immediate urgency. 

Thanks, again!
David

**Comment by SabrinaAnderson** [comment]
Not a problem. I created those views in batches and didn't realize that I had been inconsistent with the naming. We'll let you know as soon as they are ready.

**Comment by lebell** [comment]
Hi David and Jason,

We reviewed all the map view field names and found that there would be 33 changes if we capitalized all the acronyms in the field names and 17 changes if we applied camel case to all the acronyms in the field names. We were thinking we'd go the route of fewer changes, but wanted check with y'all to see what kind of an update workload these changes would create. 

Attached is our comparison spreadsheet highlighting the differences in field names and what would be changed in each view for the two options. Red = change acronym to camel case, and Blue = change acronym to all caps. 

Please let us know if you have a preference for these changes based on what you will need to update in the code. 

[171110_Schema_Update_View_Comparison.xlsx](https://github.com/TNRIS/iswp2017/files/1462703/171110_Schema_Update_View_Comparison.xlsx)


Thanks!
Laura

**Comment by DavidHickman** [comment]
This is fantastic! We don't have a particular preference for capital vs camel case, so camel case is great if that's less changes.

Thank you both!

**Comment by lebell** [comment]
The views have been updated so field names should consistently use camel case for acronyms.
