### ISSUE TITLE
Production app is using development version of React

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#249]
The production app should use the production build of React. It'll result in a smaller bundle and faster code execution client-side.

<img width="1104" alt="screen shot 2017-12-04 at 10 19 42 am" src="https://user-images.githubusercontent.com/697848/33563116-b70bb3d6-d8dc-11e7-9d50-e2757fdebd15.png">

**Comment by DavidHickman** [comment]
Hey James! Thanks for opening this issue. We are currently finalizing a series of site updates that includes updating the dependencies. When the updates are approved we'll be deploying the production site with the React 15 production build.

Did you bring me back anything from Mexico?

**Comment by jseppi** [comment]
Nice!

Only memories :)
