### ISSUE TITLE
Missing source pages

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#253]
Make sure that atmosphere, local supply, and direct reuse all display as a selectable source even though they do not have a shape associated with them.

**Comment by DavidHickman** [comment]
I think this issue refers to the WMS Type dropdown selection. Is that correct?

**Comment by lebell** [comment]
So we noticed this issue when we were testing the links in the raw data section for the new pages and found that these sources either are not hyperlinked (direct reuse) or the hyperlinks dead end (local surface water supply and atmosphere). We think these source pages may not exist because they have no shape to display on the map. So their pages should really just be a summary of related information and the source will not display a location on the map. 

None of these are currently available as options in the source drop down page, but we would like them to be. 

- Atmosphere EX: Region A page source category in raw data section - atmosphere hyperlink goes to page not found

- Local Surface Water Supply EX: Region K page source category in raw data section - local surface water supply hyperlink goes to page not found

- Direct Reuse EX: Region K page source category in raw data section - direct reuse does not have a hyperlink

**Comment by lebell** [comment]
@JasonKleinert  These are all sources- thanks for checking!

**Comment by DavidHickman** [comment]
Source ID:

Local Surface Water Supply: 412
Direct Reuse: 169

**Comment by lebell** [comment]
Thank you! Please update to done.
