### ISSUE TITLE
Add page type to section headings

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#257]
Light blue headings in each of the sections that display the selected value for the page type should have the page type concatenated with it so that the user knows which page type's data they are looking at without having to reference the URL.

This was not in our initial request, but during testing we thought it would help users know what page type they were on while they explore.

**Comment by lebell** [comment]
![pagetypeforheaders_iswp](https://user-images.githubusercontent.com/10064580/33571468-b181bf46-d8f5-11e7-8c2a-cab2d895d69b.PNG)

**Comment by DavidHickman** [comment]
*notes:*
Adding "PLANNING" to region heading, e.g. "PLANNING REGION K"
County headings will remain the same

**Comment by lebell** [comment]
Looks great, thank you! Please update to done.
