### ISSUE TITLE
MapSource update

### ISSUE THREAD

**Issue by DavidHickman** [TNRIS/iswp2017#261]
Submitted by @SabrinaAnderson via https://github.com/TNRIS/iswp2017/issues/248

Depending on how you choose to proceed with the updates, I found one other missing data item that I forgot to update. The MapSourceName is generated manually (via database change request) for each new source added to the database. I had to add a new source when making the amendment changes and forgot to create it. We can submit the data change request to get it updated now, but I doubt anyone will notice this missing source name except for me since the source name isn't hyperlinked at this time. So unless we can get it in the database while you are fixing the bugs posted above, this data refresh can wait until the next deployment of the new pages.

I've decided to wait to make the updates for that new source because it will also require an update to the shapefile used by the application in addition to a data refresh. We will work with y'all to make the changes before the next deployment to production with the new application pages. Sorry about all the missing data. SWP amendments come up once in a blue moon and this is the first time they are being made to the new DB17 database.

**Comment by lebell** [comment]
New ASR source has been added with MapSourceId - 1066 / MapSourceName - CARRIZO-WILCOX AQUIFER ASR | GONZALES. 

Please make a copy of the polygon for MapSourceId - 90 / MapSourceName - CARRIZO-WILCOX AQUIFER | GONZALES and link the new ASR source to the copied polygon to display on the iSWP. 

Thank you!
