### ISSUE TITLE
Unassigned Project Hyperlink Issue

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#262]
WMS names are showing up with hyperlinks in the table on the project page for projects that are only associated with an 'unassigned entity'. This results in the link going to a page not found page. 

Please remove the hyperlinks for these WMS names to reflect the note at the bottom of the table explaining why. 

This can be done by disabling the hyperlink functionality for WMS names related to projects, but not found in the view map.vw2017MapWMSWugSupply. 

Project names to use for examples/testing:
•	CHLORIDE CONTROL PROJECT-BRA
•	COLLEGE STATION ASR (REUSE)
•	LNVA-SRA INFRASTRUCTURE

Thank you!

**Comment by DavidHickman** [comment]
Thanks for providing test cases! I'm looking at how we can most efficiently implement this without querying for the absence of each WMS name in the map.vw2017MapWMSWugSupply view.

For each of the test project names, DisplayProjectInMap = 'N'. Would that be consistently true for these projects that should not have hyperlinks to a WMS page?

**Comment by lebell** [comment]
That's a great idea! Yes, it would be consistently true to use the DisplayProjectInMap = 'N' to select WMS names that should not have hyperlinks on the project page. Thank you for catching that.

**Comment by DavidHickman** [comment]
Awesome! This change has been deployed to staging and is ready for review.
fixed in 1815cfd9cb5d28daab109dcb197fccf96b4208c9

**Comment by SabrinaAnderson** [comment]
Looks great!
