### ISSUE TITLE
Solo feature bug in Raw Data section

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#265]
In the Raw Data section, hovering over the 'solo' button on certain fields with longer text sometimes causes line to flicker, and you are unable to click 'solo'. May be associated with column width and trying to place 'solo' on next line.

EX: WMS Type- Seawater Desalination hover over solo feature in Raw Data section. 

https://2017-staging.texasstatewaterplan.org/wmstype/SEAWATER%20DESALINATION

**Comment by DavidHickman** [comment]
Bug appears in Chrome, but not Firefox (not sure about IE). We'll look for a fix!
