### ISSUE TITLE
Add unmapped source text to About page

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#266]
Add the following bullet below the "Only the following sources are mapped…" bullet in the 'How do I use the interactive map?' section on the About page:

"If an unmapped source type (EX: Direct Reuse) has related WMS WUG supplies or a project with capital costs, it will be represented on the map by the location of the project and/or benefitting WUG."

**Comment by adambreznicky** [comment]
resolved commit 0d8bc8d5214fc112ba823f7ac67027bb6a6dc56a

**Comment by adambreznicky** [comment]
"""
misspelled benefiting with an extra “t” in the wording
"""
