### ISSUE TITLE
Remove "strategy supplies" from WMS Projects data download link

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#268]
Please remove "strategy supplies" from the download links on the WMS Projects pages. 

EX: “Download Bailey County - Muleshoe Local Groundwater Development Phase 1 WMS Project data (Comma-Separated Values)” 

instead of 

“Download Bailey County - Muleshoe Local Groundwater Development Phase 1 WMS Project Strategy Supplies data (Comma-Separated Values)”

**Comment by adambreznicky** [comment]
resolved commit eba724457499a4a403867b5217bf60502b01b0f2
