### ISSUE TITLE
About page update about projects with unassigned strategy supplies

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#270]
Change the bullet under the 'How do I use the interactive map?' section of the About page from 

"If the water management strategy water supplies for a project are not assigned to a specific water user group, then the project will not display on the map. For example, the Region L project called “Integrated Water-Power Project” will display in the list because it is a recommended project, but it does not have any WUGs associated with its strategy supplies so it will not display in the map."

to

“Information about recommended WMS projects that are not specifically associated with water user groups are displayed on the WMS Project application page although, because the water supply is not assigned to water user groups, neither the WMS project or associated supply will display on any of the other application pages until that strategy supply has been assigned to a water user group. These types of projects are recommended by the region to develop supply where a benefiting water user group has not yet been identified."

**Comment by adambreznicky** [comment]
resolved commit 982b93296503589373c7f1f937a6fc81c49d5f0e
