### ISSUE TITLE
Add instructions for filtering with 'solo' to About page

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#271]
Add the following at the bottom of the 'How do I find the information I'm looking for?' section:

"Additionally, you can filter by specific data within the table using the 'solo' feature. To do this, hover the mouse over the data element you wish to filter by until a 'solo' button appears. Selecting this feature will filter all the data in the table based on your selection. Multiple filters may be added using the same method, and all applied filters will be listed in the area above the column headers. To remove a solo filter, simply click the 'X' button to the left of the item listed in the area above the column headers."

Followed by the attached image showing the solo filtering.

**Comment by lebell** [comment]
![solo_filter_image](https://user-images.githubusercontent.com/10064580/35299760-e623a2a0-004b-11e8-883a-a661ae4faaa2.png)

**Comment by adambreznicky** [comment]
resolved in commit 8e07222326d96c26089cdcf5c0df08c6100dec19
