### ISSUE TITLE
vw2017MapSelectEntitiesInRegion.WugRegion column has extra space

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#49]
All the WugRegion values in vw2017MapSelectEntitiesInRegion are two characters wide instead of just a single character.

**Comment by wilsaj** [comment]
should we scrub fix on import for now?

**Comment by jseppi** [comment]
yes, let's fix in our import for now

**Comment by wilsaj** [comment]
![](https://media.giphy.com/media/q7UpJegIZjsk0/giphy.gif)

**Comment by jseppi** [comment]
lol

**Comment by wilsaj** [comment]
fixed!
